apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.app_port }}
  selector:
    app: {{ .Release.Name }}